/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

(* top =  1  *)
(* src = "railway_controller.v:1.1-113.10" *)
module railway_controller(clk, reset, train_arrival, train_departure, gate, warning, road_signal, state_out);
  (* src = "railway_controller.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "railway_controller.v:3.11-3.16" *)
  input reset;
  wire reset;
  (* src = "railway_controller.v:4.11-4.24" *)
  input train_arrival;
  wire train_arrival;
  (* src = "railway_controller.v:5.11-5.26" *)
  input train_departure;
  wire train_departure;
  (* src = "railway_controller.v:7.16-7.20" *)
  output gate;
  wire gate;
  (* src = "railway_controller.v:8.16-8.23" *)
  output warning;
  wire warning;
  (* src = "railway_controller.v:9.16-9.27" *)
  output road_signal;
  wire road_signal;
  (* src = "railway_controller.v:11.18-11.27" *)
  output [1:0] state_out;
  wire [1:0] state_out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "railway_controller.v:22.15-22.28" *)
  reg [1:0] current_state;
  (* src = "railway_controller.v:23.15-23.25" *)
  wire [1:0] next_state;
  assign _01_ = current_state[1] & ~(current_state[0]);
  assign _02_ = ~(train_departure & _01_);
  assign _03_ = ~(current_state[0] | current_state[1]);
  assign _00_ = ~(train_arrival & _03_);
  assign next_state[0] = ~(_02_ & _00_);
  assign gate = current_state[0] ^ current_state[1];
  (* src = "railway_controller.v:31.5-36.8" *)
  always @(posedge clk, posedge reset)
    if (reset) current_state[0] <= 1'h0;
    else current_state[0] <= next_state[0];
  (* src = "railway_controller.v:31.5-36.8" *)
  always @(posedge clk, posedge reset)
    if (reset) current_state[1] <= 1'h0;
    else current_state[1] <= gate;
  assign next_state[1] = gate;
  assign state_out = current_state;
  assign road_signal = gate;
  assign warning = gate;
endmodule
